name    'viirya-hadoop'
version '0.0.3'
author 'Liang-Chi Hsieh'
dependency 'viirya/java', '0.0.1'
summary 'Install Hadoop MapReduce Next Generation.'
description "This module deploys Hadoop MapReduce Next Generation on a cluster."
project_page 'https://github.com/viirya/puppet-hadoop'
license 'MIT License'
